ミリオンライブとシャイニーカラーズの2021年春季ライブの定義追加
imas/imasparql pull request #389
Opened 2021-01-21 11:06 UTC by mh35

2021年1月21日もくもく会でこれを実施します

2021-01-21 12:45 UTC, mh35 commented
#384 についてはこれで概ね解決かと思います

2021-01-21 12:47 UTC, subroh0508 requested changes

2021-01-21 12:47 UTC, subroh0508 commented on RDFs/Lives/Live_2021.rdf
> +    <schema:eventStatus rdf:resource="http://schema.org/EventScheduled" />
オフライン + 配信の属性が欲しいです！(他の公演も同様)

```xml
<schema:eventAttendanceMode rdf:resource="http://schema.org/MixedEventAttendanceMode" />
```

2021-01-22 16:06 UTC, crssnky approved these changes
にしこりさんの要求も入ったのでOKです！

2021-01-22 16:25 UTC, subroh0508 approved these changes
![kaho_1stlive](https://user-images.githubusercontent.com/8080435/105516980-d25fee80-5d19-11eb-9e84-e7f46dd08b49.jpg)

2021-01-22 16:25 UTC, merged