add 韓国組
imas/imasparql pull request #405
Opened 2021-03-21 15:05 UTC by crssnky

ref. #399

2021-03-21 15:13 UTC, foooomio commented
4a6231bfff1e04f0c136fa0c281f117a628f1a9f は間違いでは？

2021-03-21 15:14 UTC, crssnky commented
韓国も姓名の順番でしたっけ

2021-03-21 15:15 UTC, foooomio commented
そうです（東アジアの文化圏なので）。

2021-03-21 15:23 UTC, foooomio requested changes

2021-03-21 15:23 UTC, foooomio commented on RDFs/CinderellaGirls.rdf
> +    <schema:name xml:lang="ko">류・헤나</schema:name>
中黒はいらないと思います。

2021-03-21 15:28 UTC, foooomio requested changes

2021-03-21 15:28 UTC, foooomio commented on RDFs/CinderellaGirls.rdf
> +    <schema:name xml:lang="en">Imu Yujin</schema:name>
Im Yujin です。

2021-03-21 16:51 UTC, foooomio commented
@crssnky カスタムクエリ更新しておきました。

2021-03-21 16:51 UTC, foooomio approved these changes

2021-03-22 14:21 UTC, merged

2021-03-22 14:21 UTC, crssnky commented
助かりました！ありがとうございます！