add productions
imas/imasparql pull request #407
Opened 2021-03-23 14:52 UTC by crssnky

ref. #215

2021-03-29 12:38 UTC, foooomio commented
`schema:workLocation` の Expected Type は ContactPoint or Place なので、`schema:memberOf` とかのほうがいいんじゃないでしょうか。

https://schema.org/workLocation
https://schema.org/memberOf

あと勝手な想像ですけど、アイドルたちは事務所に「所属して」いるのであって、「働いて」いるわけではないかと思います。

2021-03-30 12:52 UTC, crssnky commented
> schema:workLocation の Expected Type は ContactPoint or Place なので、schema:memberOf とかのほうがいいんじゃないでしょうか。

親クラス(imas:Facility)の親クラスがPlaceなので、大丈夫という認識です。

> アイドルたちは事務所に「所属して」いるのであって、「働いて」いるわけではないかと思います。

たしかに、「７６５プロが"職場"です」って言われると違和感がありますね... 変更します

2021-03-30 13:35 UTC, foooomio commented
> 親クラス(imas:Facility)の親クラスがPlace

んー、なるほど。そういう意味では筋が通ってるんですね。

私が提起したかったのは、プロダクションって物理的な建物や場所だけではないんじゃないかということです。`imas:Production` は `schema:Organization` とかその子クラスの `schema:Corporation` を継承した概念（法人？）で、それが事務所やシアターのような施設を保有するという形にしたほうが自然じゃないかと思いました。

2021-03-30 13:38 UTC, crssnky commented
なるほど、法人ですか。たしかにそれなら、765プロに事務所とシアターをぶら下げられますね。その方向で変更内容を考えてみます。

2021-04-03 02:46 UTC, crssnky commented
1stVisionの方々は、765プロ所属でも良いのかなぁ...(765所属が52人ではなくなる)

2021-04-03 03:13 UTC, crssnky commented
美希は765？961？

2021-04-03 09:04 UTC, foooomio requested changes

2021-04-03 09:04 UTC, foooomio commented on RDFs/765MillionStars.rdf
> +    <schema:memberOf rdf:resource="765ProLiveTheater"/>
シアター組について、`765Production` に変更するのが適当かと思います。

2021-04-03 09:04 UTC, foooomio commented on constrains/IdolShape.ttl
> +        rdfs:comment "目的語はimas:Unit, imas:Production";
ユニットと or にするのはどういった意図でしょうか・・・？

2021-04-05 15:03 UTC, crssnky commented on constrains/IdolShape.ttl
> +        rdfs:comment "目的語はimas:Unit, imas:Production";
Unitのみだと、以下のようなプロダクション所属のためのmemberOfが怒られてしまうからです。
```xml
<schema:memberOf rdf:resource="765Production"/>
```

2021-04-05 15:30 UTC, foooomio commented on constrains/IdolShape.ttl
> +        rdfs:comment "目的語はimas:Unit, imas:Production";
あーなるほど、`schema:memberOf` は `imas:Unit` を目的語にとるのにも使っていて、今回の変更で `imas:Production` も追加になるので or にしたということですね。`sh:property` を分けたほうが見通し良さそうと思ったんですが、SHACL 的に書きづらいのであれば問題ないと思います。

2021-04-05 15:32 UTC, foooomio approved these changes

2021-04-07 14:59 UTC, crssnky commented on constrains/IdolShape.ttl
> +        rdfs:comment "目的語はimas:Unit, imas:Production";
> rdfs:label "所属ユニットの制約";

ここは変えたほうが良いかもですね。変えます

2021-04-11 13:19 UTC, foooomio approved these changes

2021-04-11 13:23 UTC, merged