オーバーキャストモノクロームに各アイドルの説明を追加
imas/imasparql pull request #416
Opened 2021-04-19 14:32 UTC by crssnky

ref. #340

2021-05-02 00:28 UTC, tankarup commented
アイドル毎に分割した変更とは別の内容になるのですが、
Overcastは1単語なのでOverCast→Overcastにするのはいかがでしょうか。

2021-05-02 07:00 UTC, crssnky commented
:naruhodo:
初めから間違っていたというわけですね...
たしかにそうでした

2021-05-03 09:50 UTC, tankarup requested changes
117行目　甘奈　雲の上→空の上
そのほかは問題なさそうでした。

2021-05-03 09:50 UTC, tankarup commented on RDFs/Clothes/ShinyColorsCommon.rdf
> +    <schema:description xml:lang="ja">ワンステップ。一緒に見たい、雲の上</schema:description>
雲の上→空の上

2021-05-03 11:06 UTC, tankarup approved these changes
修正ありがとうございます。問題なさそうです！

2021-05-03 12:24 UTC, merged