Add pop links attribute
imas/imasparql pull request #441
Opened 2021-06-18 14:26 UTC by HagiAyato

ref. #439
既にポプマス属性が登録されているアイドルと同様に、
ポプマス追加実装アイドルにもポプマス属性データを入れました。

2021-06-18 15:12 UTC, foooomio requested changes
追加ありがとうございます！

確認いたしました。一点だけご確認いただけますでしょうか。

2021-06-18 15:12 UTC, foooomio commented on RDFs/SideM.rdf
> +    <imas:PopLinksAttribute xml:lang="ja">空</imas:PopLinksAttribute>
「風(wind)」が正しいかと思います。

https://poplinks.idolmaster-official.jp/idol/detail.php?ch=oa07i0b9

2021-06-18 15:41 UTC, foooomio approved these changes
修正ありがとうございます。問題ないです。

2021-06-20 12:24 UTC, crssnky approved these changes

2021-06-20 12:25 UTC, merged