三峰結華の声優変更への対応
imas/imasparql pull request #487
Opened 2022-01-18 03:30 UTC by subroh0508

2022-01-18 04:41 UTC, crssnky commented on RDFs/283.rdf
>      <imas:cv rdf:resource="http://www.wikidata.org/entity/Q56886205"/>
こっち(Wikidata)もお願いします！

2022-01-18 06:17 UTC, foooomio requested changes
`imas:pastCv` というのがあるので使ってください。

https://github.com/imas/imasparql/blob/184e9254ee6eb8aa06efdf0ea0adecca525d1609/RDFs/SideM.rdf#L1632-L1634

2022-01-19 16:40 UTC, foooomio approved these changes

2022-01-20 11:06 UTC, crssnky approved these changes

2022-01-20 11:06 UTC, merged